### ISSUE TITLE
Unaccounted bond order 3

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [tiwarylab/GrASP#10]
Hi, it seems triple bonds are not accounted for, as I am getting this error. Is it possible?
```
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 590, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 590, in <listcomp>
    for func, args, kwargs in self.items]
  File "/content/GrASP/parse_files.py", line 690, in process_production_set
    raise e
  File "/content/GrASP/parse_files.py", line 688, in process_production_set
    process_system(mol2_dir + structure_name, save_directory=f'{prepend}/{data_dir}', parse_ligands=False)
  File "/content/GrASP/featurize_protein.py", line 225, in process_system
    edge_attributes = {tuple(bond.atoms.ids):{"bond_type":bond_type_dict[bond.order]} for bond in protein.bonds}
  File "/content/GrASP/featurize_protein.py", line 225, in <dictcomp>
    edge_attributes = {tuple(bond.atoms.ids):{"bond_type":bond_type_dict[bond.order]} for bond in protein.bonds}
KeyError: '3'
"""
```
I think it goes back to this bit here:
```
# Leaving an extra bit to denote self loops
    bond_type_dict = {
        '1': [1,0,0,0,0,0],
        '2': [0,1,0,0,0,0],
        'ar':[0,0,1,0,0,0],
        'am':[0,0,0,1,0,0],
        'un':[0,0,0,0,1,0]  # Unkown Bond Type
    }
```

**Comment by zwsmith200** [comment]
See #8 for this. There are no triple bonds in standard amino acids so we would prefer the model crashes instead of silently making predictions on a feature it has never seen.

**Comment by JavierSanchez-Utges** [comment]
Fair enough, I will check which kind of atoms and amino acids this is found in, might also be altLocs.
